# Welcome to this programming assignment
During week 1 we covered some basic numpy methods to perform basic calculations in Python. In this notebook you will be asked to complete some problems dealing with matrix and vector operations. There will be comments along the way to help you successfully complete this assignment. Good luck!

Check the [documentation](https://numpy.org/doc/1.17/reference/index.html) to find out more information about the library and methods it provides.

In [1]:
import numpy as np
import numpy.linalg as LA

## Task 1
Find the sum of all elements in an array. See [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html) for reference.

In [6]:
A = np.array([[1,13,4,5, -6],[-9,4,12,0,2],[45,4,3,2,1], [3,-9,15,6,22],[3,5,0,-7,12]])
A

array([[ 1, 13,  4,  5, -6],
       [-9,  4, 12,  0,  2],
       [45,  4,  3,  2,  1],
       [ 3, -9, 15,  6, 22],
       [ 3,  5,  0, -7, 12]])

In [7]:
ans1 = np.sum(A) #your code here

In [10]:
ans1

131

## Task 2
Calculate the difference between matrices m1 and m2.

In [12]:
m1 = np.array([[-7, -6,  3, -5],
       [ 7,  0,  4,  0],
       [ 6, -1,  1,  1]])
m2 = np.array([[  6,  -7,  -3,  -9],
       [ -8,   1,  -4,   2],
       [-10,   1,  -7,   9]])

In [13]:
ans2 = m1 - m2 #your code here

In [14]:
ans2

array([[-13,   1,   6,   4],
       [ 15,  -1,   8,  -2],
       [ 16,  -2,   8,  -8]])

## Task 3
Find the sum of all matrix elements whose absolute value is greater than 5. You can use a $\textit{for}$ loop, but try using numpy methods (i.e. [this](https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html)), since the numpy library is very fast and effective in manipulating data.

In [17]:
b = np.array([[ -6,  -7,  -5,   0],
       [-15,   2, -13,  -5],
       [  8,   4,  10,   8],
       [ -1,  -9,   7,  -4]])

In [32]:
b5 = np.where(abs(b) > 5, b, 0)
b5

array([[ -6,  -7,   0,   0],
       [-15,   0, -13,   0],
       [  8,   0,  10,   8],
       [  0,  -9,   7,   0]])

In [34]:
b5_sum = np.sum(b5)
b5_sum

-17

In [35]:
ans3 = np.sum(np.where(abs(b) > 5, b, 0)) #your code here

In [36]:
ans3

-17

In [37]:
-6-7-15-13+8+10+8-9+7


-17

## Task 4
Find the product of two matrices. Remember that it is better to use $\textit{matmul, or @,}$ for $\textbf{larger dimension}$ matrices.

In [39]:
n = np.array([[ -4,  -1,   3,  -7,   6,  -9,   5,  -9,  -7,   0],
       [-12,   3, -12,  -7,   2,  -4,   8,  13,   9,   3],
       [ -2,  -1, -15, -10,   7,   5,   7, -13,  -9,   6],
       [  7,  11,  -5,  -6,  -9,  -1,   3,  10, -15,  -6],
       [ -3,  -4,   4, -13,   4, -13,  10,  -6,  -8,  13],
       [  7, -13,  -4,   3,   4,  13, -13,   4,  -9, -10],
       [ -5,  13,  -9, -15,  11,   2,   7, -14, -14,   2],
       [ -4,  -6,  12,  10,  13,  -3,  12, -15,   5,  -2],
       [ -1,   8,   3,   7,  11,  -3,   6,  12,  12, -13],
       [ 12,  11,  12,  11,   1, -14,   2,   6,  -9,  -3]])
z = np.array([[-15,   5, -15,  10,  -3,  12,  -6, -15,   6,   3],
       [ 12,  -4,   6, -11,   5,   3,   3,  12, -15,  -6],
       [-11, -11, -10,   9,  -8, -14, -14,   7,  -2,  11],
       [  5,  -4,  11,   0,   8,  -9, -15, -11,   7, -10],
       [ -6,  -9,  -3, -13, -11,  -9,   7,  -7,   9,   4],
       [ 10,  12,   4,  -7,   1,   0,  -1,  11,  -4,  11],
       [-14,   2,  -8,  11,  -9,   5, -14,  10,  -6,  -9],
       [ -5,  10, -10,  -1,  -9, -12,  12,  14,   4,   2],
       [ -1, -13,  10,  11,  12, -14,   9,  12,  12,  -5],
       [  2,   6, -13,  -5,  -2,  -2,   0,  14,   7,  14]])

In [40]:
ans4 = np.matmul(n, z) #your code here

In [41]:
ans4

array([[-164, -172, -127,  -30, -196,  147, -106, -155, -124,   -6],
       [  81,   69,   76, -100,  -22, -170,  497,  563,   25, -201],
       [ 129,  233,  -31, -309,  -97,  515,   78, -107, -154,   58],
       [   7,  404, -228,  -84, -161,  439,   32,   16, -432, -103],
       [-342,  -41, -495,   52, -362,  185,  -98,   99,  -58,  182],
       [  55,  310,   34, -162,  -68,   71,   94, -529,  166,  214],
       [ 199,   75,  -29, -504, -196,  536,  103,   12, -473,   31],
       [-304, -524,   93,  198,  -89, -267, -521, -220,  155, -116],
       [-165, -335,  186,   58,  -41, -448,  131,  135,   93, -349],
       [-326, -174, -299,  124, -188,  -29, -388, -292,  -92, -161]])

## Task 5
Create an identity matrix of the necessary size and subtract it from A.

In [78]:
A = np.array([[  7,   8, -15,   8,  11,   7],
       [ -5,  -9,  13,  -3, -15, -11],
       [ -3,   0,  10,  -5,   3,  -8],
       [ 10,   1,   7, -11,  10,  -3],
       [ 11,   9,  -6, -14,  10, -11],
       [  6,  -4,  -4,  -9,  -6,  -7]])
A

array([[  7,   8, -15,   8,  11,   7],
       [ -5,  -9,  13,  -3, -15, -11],
       [ -3,   0,  10,  -5,   3,  -8],
       [ 10,   1,   7, -11,  10,  -3],
       [ 11,   9,  -6, -14,  10, -11],
       [  6,  -4,  -4,  -9,  -6,  -7]])

In [79]:
A.shape

(6, 6)

In [80]:
B = np.identity(6)
B

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [81]:
ans5 = np.subtract(A, np.identity(6)

In [82]:
ans5

array([[  6.,   8., -15.,   8.,  11.,   7.],
       [ -5., -10.,  13.,  -3., -15., -11.],
       [ -3.,   0.,   9.,  -5.,   3.,  -8.],
       [ 10.,   1.,   7., -12.,  10.,  -3.],
       [ 11.,   9.,  -6., -14.,   9., -11.],
       [  6.,  -4.,  -4.,  -9.,  -6.,  -8.]])

## Task 6
Find the solution to system Ax = b, use matrix inverse.

In [58]:
A = np.array([[ 0, -2,  0, -2],
       [-2,  0, -4,  4],
       [-1, -5, -2,  2],
       [ 3, 1, 2,  1]])

In [59]:
b = np.array([-4,  1,  4,  2])

In [60]:
x = np.dot(np.linalg.inv(A), b) #your code here

In [61]:
x

array([-2.45 , -0.7  ,  3.675,  2.7  ])

## Task 7
Find the PLU decomposition and assert that by multiplying the matrices in the decomposition you get the original matrix back. Submit the matrix U as the answer.

In [63]:
from scipy.linalg import lu

In [64]:
m = np.array([[ 12, -13,   2,   2, -11],
       [  1,   4,  11,  11,  -5],
       [ 13,  -5,   9,  12,  -2],
       [  5, -13,  12,   3,   5],
       [ -9,  11,  -1,  -6,  -5]])
m

array([[ 12, -13,   2,   2, -11],
       [  1,   4,  11,  11,  -5],
       [ 13,  -5,   9,  12,  -2],
       [  5, -13,  12,   3,   5],
       [ -9,  11,  -1,  -6,  -5]])

In [65]:
P, L, U = lu(m) #your code here

In [66]:
assert(np.allclose(((P@L)@U), m)) # check if we get the original matrix

In [68]:
P

array([[ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])

In [69]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.38461538,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.07692308, -0.39583333,  1.        ,  0.        ,  0.        ],
       [-0.69230769, -0.68055556,  0.80669711,  1.        ,  0.        ],
       [ 0.92307692,  0.75694444, -0.93302892, -0.14852662,  1.        ]])

In [70]:
U

array([ 13.        ,  -5.        ,   9.        ,  12.        ,
        -2.        ,   0.        , -11.07692308,   8.53846154,
        -1.61538462,   5.76923077,   0.        ,   0.        ,
        13.6875    ,   9.4375    ,  -2.5625    ,   0.        ,
         0.        ,   0.        ,  -6.40487062,  -0.39117199,
         0.        ,   0.        ,   0.        ,   0.        , -15.96981939])